version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    commands:
      - npm run start

  backend-start:
    extends:
      service: backend
    build:
      target: builder
    command: 'bash /app/dev-run.sh'
